server:
  port: 8081
  max-http-request-header-size: 16KB

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

acme:
  downstream:
    inventory-base-url: http://localhost:8082
    notification-base-url: http://localhost:8083
    connect-timeout: 2s
    read-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  simple:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
